### PR TITLE
Solution for conforming alphabetical order downloads with downloaded order

### PR DESCRIPTION
**Pull request by Boris-Ockham**
Because I copy the downloads of podcasts to an mp3-player I need the alphabetical order to be the same as the downloaded order, even when the dates of the podcasts are the same. One easy way to do this is to add " (0)" to the file name format. Because of the current change this will result in the name of the first file to be "xxxx (0)" and the second "xxxx (1)", etc.

Renaming an original "xxxx" to "xxxx (0)" when "xxxx (1)" has to be saved, would be better. One problem however is that FindFreeSaveFileName doesn't use one explicit extension. So you don't know what the filename is that has to be renamed. Beside this problem there are more consequences of renaming an already downloaded file.

To make something like {epnumber} work is much more involved than the current change.

### CODE REVIEW

**Comment by ribbons** [comment]
Wouldn't adding the hour and minute of the episode into the filename template achieve the same end result (e.g. alphabetical sort matching the date order)?

**Comment by Boris-Ockham** [comment]
It happens that the pubDate within the item-tag of the parts of one broadcast are exactly the same in the podcast for which I use the new feature. I see two times:
```xml
<pubDate>Sat, 09 Apr 2016 12:00:00 GMT</pubDate>
```
I don't see in the xml any other value which might be used. Only the order in the list differentiates the parts.

**Comment by ribbons** [comment]
What is the URL of the podcast feed?

**Comment by Boris-Ockham** [comment]
Another simpel solution would be to have file names like "xxxx.mp3" and "xxxx1.mp3" instead of "xxxx (1).mp3". I would vote for that, because having a special file name format for solving the problem doesn't look like a generic solution.

**Comment by ribbons** [comment]
> Another simpel solution would be to have file names like "xxxx.mp3" and "xxxx1.mp3" instead of "xxxx (1).mp3". I would vote for that, because having a special file name format for solving the problem doesn't look like a generic solution.

Yeah, I'm thinking along the same lines.  If you'd like to amend this PR to do that instead, I'd be happy to merge that.

**Comment by Boris-Ockham** [comment]
I'm confused about the meaning of "Merge branch 'master' ...". The problem that I wanted to solve with this was that in Visual Studio Download.cs isn't checked in after $ git commit --amend.

**Comment by ribbons** [comment]
Think you (or possibly the git client you are using) did a merge from the original pull request branch, causing both commits and a merge commit to appear.

You should be able to fix it with the below if you've not done anything since the push:

- git reset --hard ORIG_HEAD
- git push -f

HTH

**Comment by Boris-Ockham** [comment]
I did what you wrote, the merge was gone. But that had also the effect that the code changes were lost, while the new comment stayed.

I found the way to amend via Visual Studio. That caused the Merge branch 'master' appear again however. So I retried what you wrote. Now the merge stayed in the list. But it seems not to be really there. In a new screen I saw that there is no merge, and that Win32 check has failed. I have no idea what all this means, and what I should do next. :-( I suppose that I interrupted the check with my last actions.

Oh, now the check is pending...

**Comment by ribbons** [comment]
Don't worry about the AppVeyor failure, it is caused by something else (it can't access nuget.org for some reason).  I'll retry the build in a bit and it should be okay.

**Comment by Boris-Ockham** [comment]
FYI
You wrote:
> Wouldn't adding the hour and minute of the episode into the filename template achieve the same end result (e.g. alphabetical sort matching the date order)?

This turns out to be a solution for a problem with a SanDisk mp3-player which doesn't differentiate files when the names are the same for the first 28 characters or so, and the mp3-file does not contain other metadata that is different. You always hear the content of the first, while seeing the filename of the other. A filename with date and time, for example "20161003 1100 Program name.mp3" and "20161003 1105 Program name.mp3" solves that problem.

**Pull request closed without merging**
