### PR TITLE
Optional setting RadioDld.Properties.Settings.StoreConnectionString

### PR DESCRIPTION
**Pull request by Boris-Ockham**
Added optional setting RadioDld.Properties.Settings.StoreConnectionString in FetchDbConn()

### CODE REVIEW

**Comment by Boris-Ockham** [comment]
To activate this setting Radio Downloader.exe.config will look like the following:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <!-- Use proxy credentials from IE as well as proxy settings -->
    <connectionStrings>
        <add name="RadioDld.Properties.Settings.StoreConnectionString"
            connectionString="data source=C:\Users\Boris\Documents\RadioDownloaderStore.db;Version=3;New=False"
            providerName="System.Data.SQLite.EF6" />
    </connectionStrings>
    <system.net>
        <defaultProxy useDefaultCredentials="true"/>
    </system.net>
    <!-- Use version 4.0 of the .NET framework instead if 2.0 isn't available -->
    <startup useLegacyV2RuntimeActivationPolicy="true">
        <supportedRuntime version="v2.0.50727"/>
        <supportedRuntime version="v4.0" sku=".NETFramework,Version=v4.0"/>
    </startup>
</configuration>
```

**Comment by ribbons** [comment]
I'm guessing you closed this by mistake(?) so am re-opening.

Looks good, but there are a couple of improvements I can suggest:
* It would be better to fetch just the path to the database from the `<appSettings />` section, rather than the whole connection string from the `<connectionStrings />` section as this would give us the flexibility of changing part of the connection string later for all users without causing breakage to the users of this feature.
* Related to the above - then we could test if the specified folder to save the database to exists and give the user an error message rather than crashing.
* Would it be worth putting an sample for customising this into the deployed .exe.config, but commented out?

Also, some housekeeping - could you update the copyright year in the file to 2016 and add yourself to the AUTHORS.md file?

No need to open a new pull request for these changes, just amend your existing commit, force-push and your changes will show up here.

**Comment by Boris-Ockham** [comment]
The close was not a mistake. What I want is to delete everything I did. And start anew. How can I get rid of the fork I made?

**Comment by ribbons** [comment]
It is under Settings -> Danger Zone in your fork.

**Pull request closed without merging**
